[tool.poetry]
name = "hanimetv2026"
version = "1.1.2"
description = "CLI downloader tool for hanime.tv"
authors = ["BananaMan600"]
readme = "README.md"
repository = "https://github.com/BananaMan600/hanimetv2026"

[tool.poetry.dependencies]
python = "^3.6"
requests = "*"
youtube_dl = "*"

[tool.poetry.scripts]
hanimetv2026 = 'hanimetv2026.cli:main'

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
